// propertyData.js
import img1 from "./assets/1.png";
import img2 from "./assets/2.png";
import img3 from "./assets/3.png";
import img4 from "./assets/4.png";
import img5 from "./assets/5.png";
import img6 from "./assets/6.png";
import img7 from "./assets/7.png";
import img8 from "./assets/8.png";
import img9 from "./assets/9.png";
import img10 from "./assets/10.png";
import img11 from "./assets/11.png";
import img12 from "./assets/12.png";
import img13 from "./assets/13.png";
import img14 from "./assets/14.png";
import img15 from "./assets/15.png";
import img16 from "./assets/16.png";
import img17 from "./assets/17.png";
import img18 from "./assets/18.png";
import img19 from "./assets/19.png";
// import img20 from "./assets/20.png";
import img21 from "./assets/21.png";
import img22 from "./assets/22.png";
import img23 from "./assets/23.png";
import img24 from "./assets/24.png";
import img25 from "./assets/25.png";
import img26 from "./assets/26.png";
import img27 from "./assets/27.png";
import img28 from "./assets/28.png";
import img29 from "./assets/29.png";
import img30 from "./assets/30.png";
import img31 from "./assets/img31.png"
import img32 from "./assets/img32.png"
import img33 from "./assets/33.png";
import img34 from "./assets/34.png";
import img35 from "./assets/35.png";
import img36 from "./assets/36.png";
import img37 from "./assets/37.png";
import img38 from "./assets/38.png";
// import img39 from "./assets/39.png";



const propertyData = [
{
title: "ACE HANEI",
location: "Sector 12, Greater Noida West",
area: "2290-4190 sq.ft",
price: "₹ 11k/sq.ft",
config: "3/4 BHK",
img: img1,
link:"https://wa.link/z5k6pq",
type: "Apartment",
},
{
title: "MAHAGUN 2.0",
location: "Sector 12, Greater Noida West",
price: "₹ 7.64k/sq.ft",
area: "935-2190 sq.ft",
config: "2/3/4 BHK",
img: img2,
link:"https://wa.link/poia08",
type: "Apartment",
},
{
title: "ELDECO LA VIDA BELA",
location: "Sector 12, Greater Noida West",
area : "1905-3330 sq.ft",
price: "₹ 11.46k/sq.ft",
config: "3/4 BHK",
img: img3,
link:"https://wa.link/2yeip0",
type: "Apartment",
},
{ title: "BROOK & RIVULET", location: "Sector 12, Greater Noida West", img: img4 ,
area : "645-1075 sq.ft",
price: "₹ 12.1k/sq.ft",
config: "3/4 BHK",
link:"https://wa.link/ciodxs",
type: "Apartment",
},
{ title: "SPRING ELMAS", location: "Sector 12, Greater Noida West" , img: img5,
price: "₹ 11k/sq.ft",
area: "1355-2450 sq.ft",
config: "3/3.5/4 BHK",
link:"https://wa.link/ksx60s",
type: "Apartment",
},
{ title: "VVIP", location: "Sector 12, Greater Noida West" , img: img7,
price: "₹ 6.97k/sq.ft",
area: "1060-2630 sq.ft",
config: "2/2.5/3 BHK",
link:"https://wa.link/7ml3ww",
type: "Apartment",
},
{ title: "CIVITECH STRINGS", location: "Sector 12, Greater Noida West" , img: img6,
price: "₹ 10.5k/sq.ft",
area: "1090-1275 sq.ft",
config: "2/3 BHK",
link:"https://wa.link/ebk54b",
type: "Apartment",
},
{ title: "IRISH PLATINUM", location: "Sector 10" , img: img8,
price: "₹ 9.52k/sq.ft",
area: "1925-2550 sq.ft",
config: "3/4 BHK",
link:"https://wa.link/sqa2kh",
type: "Apartment",
},
{ title: "ARIHANT ABODE", location: "Sector 10" , img: img9,
price: "₹ 11.11k/sq.ft",
area: "920-1270 sq.ft",
config: "2/3/ BHK",
link:"https://wa.link/i464qb",
type: "Apartment",
},
{ title: "CRC JOYOUS", location: "Sector Techzone 4" , img: img10,
price: "₹ 16.35k/sq.ft",
area: "637-1121 sq.ft",
config: "2/3/4 BHK",
link:"https://wa.link/wo7ijg",
type: "Apartment",
},
{ title: "PANCHSHEEL GREENS 2", location: "Sector 16B" , img: img12,
price: "₹ 16.35k/sq.ft",
area: "915-1105 sq.ft",
config: "2 BHK",
link:"https://wa.link/5rd0jv",
type: "Apartment",
},
{ title: "R.G. LUXURY", location: "Sector 16B" , img: img14,
price: "₹ 8.6k/sq.ft",
area: "579-645 sq.ft",
config: "2/3 BHK",
link:"https://wa.link/6owcfd",
type: "Apartment",
},
{ title: "ELITE X", location: "Sector 10" , img: img15,
price: "₹10.65 K - 11.65 K/sq.ft",
area: "1800-2638 sq.ft",
config: "3/4 BHK",
link:"https://wa.link/vhsenb",
type: "Apartment",
},
{ title: "FRENCH APARTMENT", location: "Sector 16B" , img: img16,
price: "7.92 K - ₹9.03 K/sq.ft",
area: "1100-1300 sq.ft",
config: "2/2.5/3/4 BHK",
link:"https://wa.link/8ug2wu",
type: "Apartment",
},
{ title: "FUSION HOMES", location: "Sector Techzone 4" , img: img11,
price: "₹ 7.42k/sq.ft",
area: "888-2175 sq.ft",
config: "2/2.5/3/4/4.5 BHK",
link:"https://wa.link/bv6pm0",
type: "Apartment",
},
{ title: "PANCHSHEEL GREENS", location: "Sector 16B" , img: img13,
price: "10.23 K - ₹19.95 K/sq.ft",
area: "775-2350 sq.ft",
config: "3/4/5 BHK",
link:"https://wa.link/set9wv",
type: "Apartment",
},
{ title: "NIRALE ASPIRE", location: "Sector 16B" , img: img17,
price: "6.81 K - ₹9.15 K/sq.ft",
area: "890-2480 sq.ft",
config: "2/3 BHK",
link:"https://wa.link/f3h4qv",
type: "Apartment",
},
{ title: "ACE CITY", location: "Sector 1" , img: img18,
price: "₹7.57 K - 8.17 K/sq.ft",
area: "1080-1530 sq.ft",
config: "2/3 BHK",
link:"https://wa.link/db911e",
type: "Apartment",
},
{ title: "ROYAL COURT", location: "Sector 16B" , img: img19,
price: "6.81 K - ₹9.15 K/sq.ft",
area: "1230-1855 sq.ft",
config: "2/3 BHK",
link:"https://wa.link/xyu1c6",
type: "Apartment",
},
{ title: "CHERRY COUNTY", location: "Sector 16 Techzone 4" , img: img21,
price: "₹8.53K/sq.ft",
area: "891-2232 sq.ft",
config: "2/3/4 BHK",
link:"https://wa.link/bw6zhk",
type: "Apartment",
},
{ title: "S.K.A GREEN ARCH", location: "Sector 16B" , img: img22,
price: "₹ 10k/sq.ft",
area: "1009-1600 sq.ft",
config: "2/3 BHK",
link:"https://wa.link/gtgukg",
type: "Apartment",
},
{ title: "S.K.A DIVYA", location: "Sector 16B" , img: img23,
price: "₹ 11k/sq.ft",
area: "1260-1775 sq.ft",
config: "2/3 BHK",
link:"https://wa.link/hxpgq0",
type: "Apartment",
 },
{ title: "AMRAPALI LEISURE PARK", location: "Techzone 4" , img: img24,
price: "₹ 6.09k/sq.ft",
area: "845-1730 sq.ft",
config: "2/2.5/3 BHK",
link:"https://wa.link/rux4we",
type: "Apartment",
},
{ title: "AMRAPALI RIVER VIEW", location: "Techzone 4" , img: img25,
price: "₹ 10.6k/sq.ft",
area: "845-1145 sq.ft",
config: "2/2.5/3 BHK",
link:"https://wa.link/252xg4",
type: "Apartment",
},
{ title: "AMRAPALI GOLF HOMES", location: "Sector 4" , img: img26,
price: "₹ 3.75k/sq.ft",
area: "1157-2018 sq.ft",
config: "2/3 BHK",
link:"https://wa.link/ji3hbs",
type: "Apartment",
},
{ title: "AMRAPALI CENTURIYAN PARK O2 VALLEY", location: "Techzone 4" , img: img27,
price: "₹ 6.07k/sq.ft",
area: "1690-2950 sq.ft",
config: "2/2.5/3 BHK",
link:"https://wa.link/y3qlqt",
type: "Apartment",
},
{ title: "AMRAPALI CENTURIYAN PARK LOW RISE", location: "Techzone 4" , img: img28,
price: "₹ 7.56k/sq.ft",
area: "1055-1675 sq.ft",
config: "2/3 BHK",
link:"https://wa.link/6uycyq",
type: "Apartment",
},
{
title: "AMRAPALI CENTURIYAN PARK TERRACE",
location: "Techzone 4", img: img29,
price: "₹ 5.97k/sq.ft",
area: "885-2070 sq.ft",
config: "2/2.5/3/3.5/4 BHK",
link:"https://wa.link/ve6fz3",
type: "Apartment",
},
{ title: "AMRAPALI DREAM VALLEY", location: "Techzone 4" , img: img30,
price: "₹ 9.78k/sq.ft",
area: "1690-2950 sq.ft",
config: "3/4/5 BHK",
link:"https://wa.link/ohewl8",
type: "Apartment",
},
{
    link: "https://wa.link/00nqfr",
    img: img31,
    title: "Indo World Space Phase 1",
    location: "Ghaziabad, Uttar Pradesh",
    area: "1500 sq ft",
    price: "₹22.5k/ sq.ft",
    config: "3/4BHK",
    type: "Commercials",
  },
  {
    link: "https://wa.link/16fa60",
    img: img32,
    title: "Indo World Space Phase 2",
    location: "Ghaziabad, Uttar Pradesh",
    area: "2500 sq ft",
    price: "₹22.5K/ sq.ft",
    config: "3/4BHK",
    type: "Commercials",
  },
  {
    link: "https://wa.link/273olj",
    img: img33,
    title: "Capital Logistic",
    location: "Ghaziabad, Uttar Pradesh",
    area: "2500 sq ft",
    price: "₹22.5K/ sq.ft",
    type: "Plots",
  },
  {
    
    img: img34,
    link: "https://wa.link/f1lrha",
    title: "Sai Industrial Park Phase 1",
    location: "Ghaziabad, Uttar Pradesh",
    area: "2500 sq ft",
    price: "₹22.5K/ sq.ft",
    type: "Plots",
  },
  {
    
    link: "https://wa.link/mhemmw",
    img: img35,
    title: "Sai Industrial Park Phase 2",
    location: "Ghaziabad, Uttar Pradesh",
    area: "2500 sq ft",
    price: "₹22.5K/ sq.ft",
    type: "Plots",
  },
  {
    link: "https://wa.link/4ifxhb",
    img: img36,
    title: "Mangalam Hero Park",
    location: "Haridwar, Uttarakhand",
    area: "2500 sq ft",
    price: "₹15K/ sq.ft",
    type: "Plots",
  },
  {
   
    link: "https://wa.link/x9f8kc",
    img: img37,
    title: "MG Industrial Park",
    location: "Ghaziabad, Uttar Pradesh",
    area: "2500 sq ft",
    price: "₹15.5K/ sq.ft",
    type: "Plots",
  },
//   {
   
//     link: "https://wa.link/lfxord",
//     img: img38,
//     title: "Logi Industrial Hero Park",
//     location: "Ghaziabad, Uttar Pradesh",
//     area: "1500 sq ft",
//     price: "₹22.5k/ sq.ft",
//     type: "Plots",
//   },
];
if (!Array.isArray(propertyData) || propertyData.length === 0) {
throw new Error("No data found for the propertyData array.");
}
export default propertyData;